<a href="https://colab.research.google.com/github/Dr-Amudha/Linear-Algebra/blob/main/CrossValidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.model_selection import KFold
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [2]:
X = ["a",'b','c','d','e','f']
kf = KFold(n_splits=3,shuffle=False,random_state=None)

In [3]:
print(kf)

KFold(n_splits=3, random_state=None, shuffle=False)


In [4]:
#K-Fold Cross Validation
#i=0
for train, test in kf.split(X):
    #print("Iteration:",i)
    print("Train:",train,"Test:",test)

Train: [2 3 4 5] Test: [0 1]
Train: [0 1 4 5] Test: [2 3]
Train: [0 1 2 3] Test: [4 5]


In [5]:
#Stratified K-Fold
from sklearn.model_selection import StratifiedKFold

In [6]:
X = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
y= np.array([0,0,1,0,1,1])
skf = StratifiedKFold(n_splits=3,random_state=None,shuffle=False)

for train_index,test_index in skf.split(X,y):
    print("Train:",train_index,'Test:',test_index)
    X_train,X_test = X[train_index], X[test_index]
    y_train,y_test = y[train_index], y[test_index]

Train: [1 3 4 5] Test: [0 2]
Train: [0 2 3 5] Test: [1 4]
Train: [0 1 2 4] Test: [3 5]


In [7]:
#Leave One Out Cross Validation
from sklearn.model_selection import LeaveOneOut
X = [10,20,30,40,50,60,70,80,90,100]
l = LeaveOneOut()

for train, test in l.split(X):
    print("%s %s"% (train,test))

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [8]:
#Hold Out Cross Validation
from sklearn.model_selection import train_test_split
X = [10,20,30,40,50,60,70,80,90,100]

train, test= train_test_split(X,test_size=0.3, random_state=1)
print("Train:",X_train,"Test:" ,X_test)

Train: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]] Test: [[ 7  8]
 [11 12]]


In [9]:
data = pd.read_csv('/content/sample_data/data.csv')

In [10]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [11]:
data.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [12]:
data = data.drop(['Unnamed: 32'], axis=1)



Id feature will not be of any use for our model.

So I will drop it.

The data doesn't have any null values.

I will go ahead with model building without doing any exploratory data analysis as this is a widely used data.

And our purpose is to evaluate different cross validation techniques on the model

Our aim is to predict the severity of cancer based on the input features.

So we can use Decision trees to solve this classification problem


In [13]:
data['diagnosis'].nunique()

2

In [14]:
data['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [15]:
X = data.drop(['id','diagnosis'], axis=1)
y = data['diagnosis']

In [16]:
#Hold One Out Method
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)
dt = DecisionTreeClassifier()
dtmodel = dt.fit(X_train,y_train)
dt.score(X_train,y_train)



1.0

In [17]:
hoo_result = dtmodel.score(X_test,y_test)
print("The accuracy score is for Hold one out method :",hoo_result)

The accuracy score is for Hold one out method : 0.9473684210526315


In [18]:
#K-Fold Method
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import accuracy_score
dt = DecisionTreeClassifier()
kf= KFold(n_splits=5)
kfold_score = cross_val_score(dt,X,y,cv=kf)
print("The cross validation scores of k-fold method with 5 folds is",kfold_score)


The cross validation scores of k-fold method with 5 folds is [0.89473684 0.9122807  0.93859649 0.92982456 0.85840708]


In [19]:
kfold_score_mean = kfold_score.mean()

In [20]:
print("The min accuracy from k-fold CV is",min(kfold_score))
print("The max accuracy from k-fold CV is", max(kfold_score))
print("The mean cross validation scores of k-fold method with 5 folds is",kfold_score_mean)

The min accuracy from k-fold CV is 0.8584070796460177
The max accuracy from k-fold CV is 0.9385964912280702
The mean cross validation scores of k-fold method with 5 folds is 0.9067691352274491


In [21]:
#complete implementation of k-fold cross validation
kf2=KFold(n_splits=5)
acc_score_kfold = []
for train_ind,test_ind in kf2.split(X,y):
    #print("Train:",train_ind,'Test:',test_ind)
    X_train,X_test = X.iloc[train_ind,:], X.iloc[test_ind,:]
    y_train,y_test = y[train_ind], y[test_ind]
    
    dt.fit(X_train,y_train)
    pred_values = dt.predict(X_test)
     
    acc = accuracy_score(pred_values , y_test)
    acc_score_kfold.append(acc)
     
avg_acc_score = sum(acc_score_kfold)/5
 
print('accuracy of each fold : {}'.format(acc_score_kfold))
print('Avg accuracy : {}'.format(avg_acc_score))

accuracy of each fold : [0.8596491228070176, 0.9035087719298246, 0.9473684210526315, 0.9385964912280702, 0.8672566371681416]
Avg accuracy : 0.903275888837137


In [22]:
#Stratified K-Fold method
from sklearn.model_selection import StratifiedKFold
skfold = StratifiedKFold(n_splits=10)
skfold_score = cross_val_score(dt,X,y,cv=skfold)
print("The accuracy of Stratified k-fold method with 10 folds is",skfold_score)

The accuracy of Stratified k-fold method with 10 folds is [0.96491228 0.87719298 0.9122807  0.89473684 0.96491228 0.89473684
 0.9122807  0.94736842 0.92982456 0.92857143]


In [23]:
skfold_score_mean = skfold_score.mean()
print("The accuracy of Stratifieid k-fold method with 10 folds is",skfold_score_mean)

The accuracy of Stratifieid k-fold method with 10 folds is 0.9226817042606517


In [24]:
#Leave One Out Method
from sklearn.model_selection import LeaveOneOut
loocv = LeaveOneOut()
loocv_score = cross_val_score(dt,X,y,cv=loocv)
print("The accuracy of Leave one out method is",loocv_score)



The accuracy of Leave one out method is [1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1

In [25]:
loocv_score_mean = loocv_score.mean()
print("The average accuracy of Leave one out method with is",loocv_score_mean)

The average accuracy of Leave one out method with is 0.929701230228471
