In [1]:
# Libraries for this section 
import numpy as np
import pandas as pd
import altair as alt
alt.themes.enable('dark')


ThemeRegistry.enable('dark')

In [2]:
x = np.array([[1],
              [2],
              [3]])


In [3]:
x.shape # (3 dimensions, 1 element on each)

(3, 1)

In [4]:
print(f'A 3-dimensional vector:\n{x}')


A 3-dimensional vector:
[[1]
 [2]
 [3]]


In [5]:
#Basic Vector Operations
x = y = np.array([[1],
                  [2],
                  [3]])


In [6]:
x + y


array([[2],
       [4],
       [6]])

In [7]:
np.add(x,y)


array([[2],
       [4],
       [6]])

In [8]:
#Vector Scalar Multiplications
alpha = 2
x = np.array([[1],
             [2],
             [3]])


In [9]:
alpha * x


array([[2],
       [4],
       [6]])

In [10]:
#Linear combinations of vectors
a, b = 2, 3
x , y = np.array([[2],[3]]), np.array([[4], [5]])


In [11]:
a*x + b*y


array([[16],
       [21]])

In [12]:
#Vector-vector multiplication: dot product
x, y = np.array([[-2],[2]]), np.array([[4],[-3]])


In [13]:
x.T @ y


array([[-14]])

In [14]:
#Matrices
# Libraries for this section 
import numpy as np
import pandas as pd
import altair as alt


In [15]:
A = np.array([[0,2],  # 1st row
              [1,4]]) # 2nd row

print(f'a 2x2 Matrix:\n{A}')


a 2x2 Matrix:
[[0 2]
 [1 4]]


In [16]:
#Matrix Addition
A = np.array([[0,2],
              [1,4]])
B = np.array([[3,1],
              [-3,2]])
A+B

array([[ 3,  3],
       [-2,  6]])

In [17]:
#Matrix-scalar multiplication
alpha = 2
A = np.array([[1,2],
              [3,4]])
alpha * A


array([[2, 4],
       [6, 8]])

In [18]:
np.multiply(alpha, A)


array([[2, 4],
       [6, 8]])

In [19]:
#Matrix-vector multiplication: dot product
A = np.array([[0,2],
              [1,4]])
x = np.array([[1],
              [2]])
A @ x


array([[4],
       [9]])

In [20]:
np.dot(A, x)


array([[4],
       [9]])

In [21]:
#Matrix-matrix multiplication
A = np.array([[0,2],
              [1,4]])
B = np.array([[1,3],
              [2,1]])
A @ B


array([[4, 2],
       [9, 7]])

In [22]:
#Matrix transpose
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
A.T


array([[1, 3, 5],
       [2, 4, 6]])